### ISSUE TITLE
How this project is related to CSharpFunctionalExtensions?

### ISSUE THREAD

**Issue by Prologh** [amantinband/error-or#103]
Was it inspired by it? Would you say it's better? Or maybe what differences it provides in comparison to [CSharpFunctionalExtensions](https://github.com/vkhorikov/CSharpFunctionalExtensions)?

**Comment by amantinband** [comment]
Hey @Prologh! CSharpFunctionalExtensions is a great project.

ErrorOr provides similar functionality with the main goal of being intuitive, practical and fast, which is why the naming is fluent and there are various error types and result types out of the box.

Check out the README for all the features, there are quite a few features that aren't offered by CSharpFunctionalExtensions and vice versa

**Comment by Prologh** [comment]
Thanks for response. I did see the README, so I will check out the exact differences on my own.

How about the history of this project? I'm just curious. I hope you don't mind sharing some details about initial thoughts that get you started with this library. Just a brief note would be more than enough, thanks!

**Comment by amantinband** [comment]
Was using OneOf for a while and it wasn't scaling well with multiple errors. I also missed some of the other functionality that I originally added to the library such as known error types, known result types etc'

https://github.com/amantinband/error-or/blob/dcf61226866f243e53cf67819bd7160120795b02/README.md?plain=1#L760-L762

**Comment by Prologh** [comment]
That's interesting how you followed up on that. I think I satisfied my curiosity now, so I'm closing this issue. Cheers.
