### ISSUE TITLE
Add error levels (Warning, Fatal, Error...)

### ISSUE THREAD

**Issue by bellons91** [amantinband/error-or#46]
Say that you are processing a collection of items: for each item, you need to contact an external service accessible under authentication.

There are then different levels of errors: "fatal", for errors as "authentication failed" (this error will occur for each item in the list), and "warning", such as "this item does not exist".

We should be able to handle errors based on their levels

**Comment by amantinband** [comment]
Hey Davide! I don't have plans to add a feature like this since I want to encourage devs using this package to explicitly check against expected errors.

So basically this
```cs
if (result.Errors.Contains(error => error.ErrorLevel == ErrorLevel.Fatal)
{
    return result.Errors;
}
```

would have to look something like this
```cs
if (result.FirstError == GithubErrors.Unauthorized)
{
    // log necessary details
    return Error.Unexpected(description: "Authentication against GitHub unexpectedly failed");
}
```

Although less generic, I think the overall cognitive load of a project is lower this way. What do you think?

**Comment by amantinband** [comment]
Version `1.4.0` added the `Metadata` property to errors which enables storing extra properties alongside the error. You can use this property to store an ErrorLevel for each of your errors. If you still think this should exist natively in the error, feel free to reopen the issue and let's discuss it :)
